[workspace]
resolver = "2"
members = [
    "lame-graphics",
    "lame-macros",
]
exclude = []

[lib]

[package]
name = "lame"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"
keywords = ["graphics"]
license = "MIT"

[dependencies]
lame-macros = { version = "0.1", path = "lame-macros" }
lame-graphics = { version = "0.1", path = "lame-graphics" }

[dev-dependencies]
env_logger = "0.9"
rand = "0.8"
winit = "0.27"
