[workspace]
resolver = "2"
members = [
    "blade-graphics",
    "blade-macros",
]
exclude = []

[lib]

[package]
name = "blade"
description = "Sharp and simple graphics library"
version = "0.0.1"
edition = "2021"
rust-version = "1.65"
keywords = ["graphics"]
license = "MIT"
repository = "https://github.com/kvark/blade"
readme = "docs/README.md"

[dependencies]
#blade-macros = { version = "0.0.1", path = "blade-macros" }
blade-graphics = { version = "0.0.1", path = "blade-graphics" }

[dev-dependencies]
env_logger = "0.9"
rand = "0.8"
winit = "0.27"
